# Generated by Django 4.0.2 on 2022-02-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('value', 'voter', 'year'), name='value_voter_year'),
        ),
    ]
