# Generated by Django 4.0.2 on 2022-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_voter_id_alter_voter_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='value_voter_year',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'year'), name='voter_year'),
        ),
    ]
