# Generated by Django 4.0.2 on 2022-03-02 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_remove_vote_value_voter_year_vote_voter_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('year', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
